"""registrations, outbox

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 17:13:47.414929

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Порядок постановки в лист ожидания (R-4); autogenerate последовательности не видит.
    op.execute(sa.schema.CreateSequence(sa.Sequence("registrations_waitlist_seq")))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("ticket_code", sa.String(length=10), nullable=True),
        sa.Column("waitlist_seq", sa.BigInteger(), nullable=True),
        sa.Column("waitlisted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'confirmed' OR ticket_code IS NOT NULL", name="confirmed_has_ticket"
        ),
        sa.CheckConstraint(
            "status <> 'waitlisted' OR waitlist_seq IS NOT NULL", name="waitlisted_has_seq"
        ),
        sa.CheckConstraint(
            "status IN ('confirmed', 'waitlisted', 'cancelled')", name="registration_status"
        ),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "email", name="uq_registrations_event_email"),
        sa.UniqueConstraint("ticket_code"),
    )
    op.create_index(
        "ix_registrations_event_status", "registrations", ["event_id", "status"], unique=False
    )
    op.create_index(op.f("ix_registrations_user_id"), "registrations", ["user_id"], unique=False)
    op.create_table(
        "outbox_emails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("to_email", sa.String(length=320), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("registration_id", sa.Integer(), nullable=True),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["registration_id"], ["registrations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(op.f("ix_outbox_emails_to_email"), "outbox_emails", ["to_email"], unique=False)
    op.add_column(
        "events",
        sa.Column("schedule_version", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "schedule_version")
    op.drop_index(op.f("ix_outbox_emails_to_email"), table_name="outbox_emails")
    op.drop_table("outbox_emails")
    op.drop_index(op.f("ix_registrations_user_id"), table_name="registrations")
    op.drop_index("ix_registrations_event_status", table_name="registrations")
    op.drop_table("registrations")
    # ### end Alembic commands ###
    op.execute(sa.schema.DropSequence(sa.Sequence("registrations_waitlist_seq")))
