"""checkin

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-07 08:54:20.159351

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "registrations", sa.Column("checked_in_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###
    # autogenerate не сравнивает CHECK-ограничения — добавлено вручную.
    op.create_check_constraint(
        "checked_in_is_confirmed", "registrations", "checked_in_at IS NULL OR status = 'confirmed'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("checked_in_is_confirmed", "registrations", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("registrations", "checked_in_at")
    # ### end Alembic commands ###
